- id: deno-eval
  name: deno-eval
  language: deno
  entry: deno-hooks eval
  pass_filenames: false
- id: deno-semver
  name: deno-semver
  language: deno
  entry: deno-hooks semver
  pass_filenames: false
