- id: deno-eval
  name: deno-eval
  language: deno
  entry: deno-hooks eval
  additional_dependencies:
    - ./cli.ts:deno-hooks
  pass_filenames: false
- id: deno-semver
  name: deno-semver
  language: deno
  entry: semver-tool 1.2.3
  pass_filenames: false
- id: deno-local-dep
  name: deno-local-dep
  language: deno
  entry: echo-tool
  additional_dependencies:
    - ./local-tool.ts:echo-tool
  pass_filenames: false
